// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kernel_def.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Vision.Tensorflow.Proto {

  /// <summary>Holder for reflection information generated from kernel_def.proto</summary>
  public static partial class KernelDefReflection {

    #region Descriptor
    /// <summary>File descriptor for kernel_def.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KernelDefReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBrZXJuZWxfZGVmLnByb3RvEgp0ZW5zb3JmbG93GhBhdHRyX3ZhbHVlLnBy",
            "b3RvIt0BCglLZXJuZWxEZWYSCgoCb3AYASABKAkSEwoLZGV2aWNlX3R5cGUY",
            "AiABKAkSOAoKY29uc3RyYWludBgDIAMoCzIkLnRlbnNvcmZsb3cuS2VybmVs",
            "RGVmLkF0dHJDb25zdHJhaW50EhcKD2hvc3RfbWVtb3J5X2FyZxgEIAMoCRIN",
            "CgVsYWJlbBgFIAEoCRpNCg5BdHRyQ29uc3RyYWludBIMCgRuYW1lGAEgASgJ",
            "Ei0KDmFsbG93ZWRfdmFsdWVzGAIgASgLMhUudGVuc29yZmxvdy5BdHRyVmFs",
            "dWVCMAoYb3JnLnRlbnNvcmZsb3cuZnJhbWV3b3JrQg9LZXJuZWxEZWZQcm90",
            "b3NQAfgBAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Vision.Tensorflow.Proto.AttrValueReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Vision.Tensorflow.Proto.KernelDef), global::Vision.Tensorflow.Proto.KernelDef.Parser, new[]{ "Op", "DeviceType", "Constraint", "HostMemoryArg", "Label" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Vision.Tensorflow.Proto.KernelDef.Types.AttrConstraint), global::Vision.Tensorflow.Proto.KernelDef.Types.AttrConstraint.Parser, new[]{ "Name", "AllowedValues" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class KernelDef : pb::IMessage<KernelDef> {
    private static readonly pb::MessageParser<KernelDef> _parser = new pb::MessageParser<KernelDef>(() => new KernelDef());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<KernelDef> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Vision.Tensorflow.Proto.KernelDefReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KernelDef() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KernelDef(KernelDef other) : this() {
      op_ = other.op_;
      deviceType_ = other.deviceType_;
      constraint_ = other.constraint_.Clone();
      hostMemoryArg_ = other.hostMemoryArg_.Clone();
      label_ = other.label_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public KernelDef Clone() {
      return new KernelDef(this);
    }

    /// <summary>Field number for the "op" field.</summary>
    public const int OpFieldNumber = 1;
    private string op_ = "";
    /// <summary>
    /// Must match the name of an Op.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Op {
      get { return op_; }
      set {
        op_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device_type" field.</summary>
    public const int DeviceTypeFieldNumber = 2;
    private string deviceType_ = "";
    /// <summary>
    /// Type of device this kernel runs on.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeviceType {
      get { return deviceType_; }
      set {
        deviceType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "constraint" field.</summary>
    public const int ConstraintFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Vision.Tensorflow.Proto.KernelDef.Types.AttrConstraint> _repeated_constraint_codec
        = pb::FieldCodec.ForMessage(26, global::Vision.Tensorflow.Proto.KernelDef.Types.AttrConstraint.Parser);
    private readonly pbc::RepeatedField<global::Vision.Tensorflow.Proto.KernelDef.Types.AttrConstraint> constraint_ = new pbc::RepeatedField<global::Vision.Tensorflow.Proto.KernelDef.Types.AttrConstraint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Vision.Tensorflow.Proto.KernelDef.Types.AttrConstraint> Constraint {
      get { return constraint_; }
    }

    /// <summary>Field number for the "host_memory_arg" field.</summary>
    public const int HostMemoryArgFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_hostMemoryArg_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> hostMemoryArg_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Names of the Op's input_/output_args that reside in host memory
    /// instead of device memory.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> HostMemoryArg {
      get { return hostMemoryArg_; }
    }

    /// <summary>Field number for the "label" field.</summary>
    public const int LabelFieldNumber = 5;
    private string label_ = "";
    /// <summary>
    /// This allows experimental kernels to be registered for an op that
    /// won't be used unless the user specifies a "_kernel" attr with
    /// value matching this.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Label {
      get { return label_; }
      set {
        label_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as KernelDef);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(KernelDef other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Op != other.Op) return false;
      if (DeviceType != other.DeviceType) return false;
      if(!constraint_.Equals(other.constraint_)) return false;
      if(!hostMemoryArg_.Equals(other.hostMemoryArg_)) return false;
      if (Label != other.Label) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Op.Length != 0) hash ^= Op.GetHashCode();
      if (DeviceType.Length != 0) hash ^= DeviceType.GetHashCode();
      hash ^= constraint_.GetHashCode();
      hash ^= hostMemoryArg_.GetHashCode();
      if (Label.Length != 0) hash ^= Label.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Op.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Op);
      }
      if (DeviceType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceType);
      }
      constraint_.WriteTo(output, _repeated_constraint_codec);
      hostMemoryArg_.WriteTo(output, _repeated_hostMemoryArg_codec);
      if (Label.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Label);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Op.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Op);
      }
      if (DeviceType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceType);
      }
      size += constraint_.CalculateSize(_repeated_constraint_codec);
      size += hostMemoryArg_.CalculateSize(_repeated_hostMemoryArg_codec);
      if (Label.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Label);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(KernelDef other) {
      if (other == null) {
        return;
      }
      if (other.Op.Length != 0) {
        Op = other.Op;
      }
      if (other.DeviceType.Length != 0) {
        DeviceType = other.DeviceType;
      }
      constraint_.Add(other.constraint_);
      hostMemoryArg_.Add(other.hostMemoryArg_);
      if (other.Label.Length != 0) {
        Label = other.Label;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Op = input.ReadString();
            break;
          }
          case 18: {
            DeviceType = input.ReadString();
            break;
          }
          case 26: {
            constraint_.AddEntriesFrom(input, _repeated_constraint_codec);
            break;
          }
          case 34: {
            hostMemoryArg_.AddEntriesFrom(input, _repeated_hostMemoryArg_codec);
            break;
          }
          case 42: {
            Label = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the KernelDef message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class AttrConstraint : pb::IMessage<AttrConstraint> {
        private static readonly pb::MessageParser<AttrConstraint> _parser = new pb::MessageParser<AttrConstraint>(() => new AttrConstraint());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<AttrConstraint> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Vision.Tensorflow.Proto.KernelDef.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AttrConstraint() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AttrConstraint(AttrConstraint other) : this() {
          name_ = other.name_;
          AllowedValues = other.allowedValues_ != null ? other.AllowedValues.Clone() : null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AttrConstraint Clone() {
          return new AttrConstraint(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        /// <summary>
        /// Name of an attr from the Op.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "allowed_values" field.</summary>
        public const int AllowedValuesFieldNumber = 2;
        private global::Vision.Tensorflow.Proto.AttrValue allowedValues_;
        /// <summary>
        /// A list of values that this kernel supports for this attr.
        /// Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Vision.Tensorflow.Proto.AttrValue AllowedValues {
          get { return allowedValues_; }
          set {
            allowedValues_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as AttrConstraint);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(AttrConstraint other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if (!object.Equals(AllowedValues, other.AllowedValues)) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (allowedValues_ != null) hash ^= AllowedValues.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          if (allowedValues_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(AllowedValues);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (allowedValues_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(AllowedValues);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(AttrConstraint other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.allowedValues_ != null) {
            if (allowedValues_ == null) {
              allowedValues_ = new global::Vision.Tensorflow.Proto.AttrValue();
            }
            AllowedValues.MergeFrom(other.AllowedValues);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 18: {
                if (allowedValues_ == null) {
                  allowedValues_ = new global::Vision.Tensorflow.Proto.AttrValue();
                }
                input.ReadMessage(allowedValues_);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
