// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow.Grpc {

  /// <summary>Holder for reflection information generated from master_service.proto</summary>
  public static partial class MasterServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for master_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MasterServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRtYXN0ZXJfc2VydmljZS5wcm90bxIPdGVuc29yZmxvdy5ncnBjGgxtYXN0",
            "ZXIucHJvdG8yvAQKDU1hc3RlclNlcnZpY2USVAoNQ3JlYXRlU2Vzc2lvbhIg",
            "LnRlbnNvcmZsb3cuQ3JlYXRlU2Vzc2lvblJlcXVlc3QaIS50ZW5zb3JmbG93",
            "LkNyZWF0ZVNlc3Npb25SZXNwb25zZRJUCg1FeHRlbmRTZXNzaW9uEiAudGVu",
            "c29yZmxvdy5FeHRlbmRTZXNzaW9uUmVxdWVzdBohLnRlbnNvcmZsb3cuRXh0",
            "ZW5kU2Vzc2lvblJlc3BvbnNlEloKD1BhcnRpYWxSdW5TZXR1cBIiLnRlbnNv",
            "cmZsb3cuUGFydGlhbFJ1blNldHVwUmVxdWVzdBojLnRlbnNvcmZsb3cuUGFy",
            "dGlhbFJ1blNldHVwUmVzcG9uc2USQgoHUnVuU3RlcBIaLnRlbnNvcmZsb3cu",
            "UnVuU3RlcFJlcXVlc3QaGy50ZW5zb3JmbG93LlJ1blN0ZXBSZXNwb25zZRJR",
            "CgxDbG9zZVNlc3Npb24SHy50ZW5zb3JmbG93LkNsb3NlU2Vzc2lvblJlcXVl",
            "c3QaIC50ZW5zb3JmbG93LkNsb3NlU2Vzc2lvblJlc3BvbnNlEk4KC0xpc3RE",
            "ZXZpY2VzEh4udGVuc29yZmxvdy5MaXN0RGV2aWNlc1JlcXVlc3QaHy50ZW5z",
            "b3JmbG93Lkxpc3REZXZpY2VzUmVzcG9uc2USPAoFUmVzZXQSGC50ZW5zb3Jm",
            "bG93LlJlc2V0UmVxdWVzdBoZLnRlbnNvcmZsb3cuUmVzZXRSZXNwb25zZUIz",
            "ChpvcmcudGVuc29yZmxvdy5kaXN0cnVudGltZUITTWFzdGVyU2VydmljZVBy",
            "b3Rvc1ABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Vision.Tensorflow.Proto.MasterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
