// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tensorflow.Grpc {

  /// <summary>Holder for reflection information generated from worker_service.proto</summary>
  public static partial class WorkerServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for worker_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorkerServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChR3b3JrZXJfc2VydmljZS5wcm90bxIPdGVuc29yZmxvdy5ncnBjGgx3b3Jr",
            "ZXIucHJvdG8ymQcKDVdvcmtlclNlcnZpY2USSAoJR2V0U3RhdHVzEhwudGVu",
            "c29yZmxvdy5HZXRTdGF0dXNSZXF1ZXN0Gh0udGVuc29yZmxvdy5HZXRTdGF0",
            "dXNSZXNwb25zZRJmChNDcmVhdGVXb3JrZXJTZXNzaW9uEiYudGVuc29yZmxv",
            "dy5DcmVhdGVXb3JrZXJTZXNzaW9uUmVxdWVzdBonLnRlbnNvcmZsb3cuQ3Jl",
            "YXRlV29ya2VyU2Vzc2lvblJlc3BvbnNlEmYKE0RlbGV0ZVdvcmtlclNlc3Np",
            "b24SJi50ZW5zb3JmbG93LkRlbGV0ZVdvcmtlclNlc3Npb25SZXF1ZXN0Gicu",
            "dGVuc29yZmxvdy5EZWxldGVXb3JrZXJTZXNzaW9uUmVzcG9uc2USVAoNUmVn",
            "aXN0ZXJHcmFwaBIgLnRlbnNvcmZsb3cuUmVnaXN0ZXJHcmFwaFJlcXVlc3Qa",
            "IS50ZW5zb3JmbG93LlJlZ2lzdGVyR3JhcGhSZXNwb25zZRJaCg9EZXJlZ2lz",
            "dGVyR3JhcGgSIi50ZW5zb3JmbG93LkRlcmVnaXN0ZXJHcmFwaFJlcXVlc3Qa",
            "Iy50ZW5zb3JmbG93LkRlcmVnaXN0ZXJHcmFwaFJlc3BvbnNlEkUKCFJ1bkdy",
            "YXBoEhsudGVuc29yZmxvdy5SdW5HcmFwaFJlcXVlc3QaHC50ZW5zb3JmbG93",
            "LlJ1bkdyYXBoUmVzcG9uc2USUQoMQ2xlYW51cEdyYXBoEh8udGVuc29yZmxv",
            "dy5DbGVhbnVwR3JhcGhSZXF1ZXN0GiAudGVuc29yZmxvdy5DbGVhbnVwR3Jh",
            "cGhSZXNwb25zZRJLCgpDbGVhbnVwQWxsEh0udGVuc29yZmxvdy5DbGVhbnVw",
            "QWxsUmVxdWVzdBoeLnRlbnNvcmZsb3cuQ2xlYW51cEFsbFJlc3BvbnNlEk0K",
            "ClJlY3ZUZW5zb3ISHS50ZW5zb3JmbG93LlJlY3ZUZW5zb3JSZXF1ZXN0Gh4u",
            "dGVuc29yZmxvdy5SZWN2VGVuc29yUmVzcG9uc2UiABJCCgdMb2dnaW5nEhou",
            "dGVuc29yZmxvdy5Mb2dnaW5nUmVxdWVzdBobLnRlbnNvcmZsb3cuTG9nZ2lu",
            "Z1Jlc3BvbnNlEkIKB1RyYWNpbmcSGi50ZW5zb3JmbG93LlRyYWNpbmdSZXF1",
            "ZXN0GhsudGVuc29yZmxvdy5UcmFjaW5nUmVzcG9uc2VCMwoab3JnLnRlbnNv",
            "cmZsb3cuZGlzdHJ1bnRpbWVCE1dvcmtlclNlcnZpY2VQcm90b3NQAWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Vision.Tensorflow.Proto.WorkerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
